[package]
name = "enum-iterator-derive"
version = "0.3.0"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
edition = "2018"
description = """Procedural macro to iterate over the variants of a \
    field-less enum"""
license = "MIT"
homepage = "https://github.com/stephaneyfx/enum-iterator"
repository = "https://github.com/stephaneyfx/enum-iterator.git"
documentation = "https://docs.rs/enum-iterator-derive"
keywords = ["enum", "variants", "iterator"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.26"
quote = "0.6.11"
syn = "0.15.26"
