[package]
name = "enum-iterator-derive"
version = "0.2.1"
authors = ["Stephane Raux <stephaneyfx@gmail.com>"]
description = """Procedural macro to iterate over the variants of a \
    field-less enum"""
license = "MIT"
homepage = "https://github.com/stephaneyfx/enum-iterator"
repository = "https://github.com/stephaneyfx/enum-iterator.git"
documentation = "https://docs.rs/enum-iterator-derive"
keywords = ["enum", "variants", "iterator"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "0.4.6"
quote = "0.6.3"
syn = "0.14.2"
